/**
 * Render Jest-style test source (works with Vitest with --runner vitest + minor edits).
 */

export function renderSuite({
  operations,
  runner = 'jest',
  client = 'fetch',
  title = 'Generated API tests',
}) {
  const hdr = `/**
 * ${title}
 * Generated by apitest-gen — review and add real assertions.
 * Set API_BASE_URL (required). Optional: API_AUTH_HEADER (e.g. "Bearer xxx").
 */
`

  const setup =
    runner === 'vitest'
      ? `import { describe, it, expect, beforeAll } from 'vitest'

const baseUrl = () => process.env.API_BASE_URL || ''
const authHeader = () => process.env.API_AUTH_HEADER || ''

async function apiRequest(method, path, init = {}) {
  const base = baseUrl().replace(/\\/?$/, '/')
  const rel = path.replace(/^\\//, '')
  const url = new URL(rel, base)
  const headers = { ...(init.headers || {}) }
  const auth = authHeader()
  if (auth) headers['Authorization'] = auth
  return fetch(url, { ...init, method, headers })
}
`
      : `const baseUrl = () => process.env.API_BASE_URL || ''
const authHeader = () => process.env.API_AUTH_HEADER || ''

async function apiRequest(method, path, init = {}) {
  const base = baseUrl().replace(/\\/?$/, '/')
  const rel = path.replace(/^\\//, '')
  const url = new URL(rel, base)
  const headers = { ...(init.headers || {}) }
  const auth = authHeader()
  if (auth) headers['Authorization'] = auth
  return fetch(url, { ...init, method, headers })
}
`

  const blocks = operations.map((op) => renderOperation(op, client))

  const suite = `${hdr}${setup}

describe('${escapeString(title)}', () => {
  beforeAll(() => {
    if (!baseUrl()) {
      throw new Error('Set API_BASE_URL before running these tests.')
    }
  })

${blocks.join('\n\n')}
})
`

  return suite
}

function renderOperation(op, client) {
  if (client !== 'fetch') {
    throw new Error(`Only client=fetch is supported in v0.1 (got ${client})`)
  }

  const name = `${op.method} ${op.pathTemplate}`
  const pathForCall = /\{[^}]+\}/.test(op.resolvedPath)
    ? op.pathTemplate
    : op.resolvedPath

  const query =
    op.queryParams.length > 0
      ? `?${op.queryParams.map((q) => `${encodeURIComponent(q.name)}=${encodeURIComponent(String(q.example))}`).join('&')}`
      : ''

  const requestInit = buildRequestInit(op)
  const assertions = buildResponseAssertions(op)

  const itBody = `      const res = await apiRequest('${op.method}', '${pathForCall}${query}'${requestInit})
${assertions}`

  return `  describe('${escapeString(name)}', () => {
    it('responds (${op.operationId})', async () => {
${itBody}
    })
  })`
}

/** @param {Record<string, unknown> & { bodyExample?: unknown, bodyContentType?: string | null, hasBody?: boolean, method: string }} op */
function buildRequestInit(op) {
  const wantsBody =
    op.hasBody &&
    ['POST', 'PUT', 'PATCH', 'DELETE'].includes(op.method)

  if (!wantsBody) return ''

  const ct = op.bodyContentType || 'application/json'

  if (op.bodyExample !== null && op.bodyExample !== undefined) {
    const embedded = JSON.stringify(op.bodyExample)
    return `, { headers: { 'Content-Type': '${ct}' }, body: JSON.stringify(${embedded}) }`
  }

  return `, { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({}) } // TODO: add requestBody example in OpenAPI — ${op.summary || 'document request body'}`
}

/** @param {Record<string, unknown> & { expectedStatus?: number, responseExample?: unknown }} op */
function buildResponseAssertions(op) {
  const status = op.expectedStatus ?? 200
  const lines = [`      expect(res.status).toBe(${status})`]

  if (status === 204) {
    lines.push(`      return`)
    return lines.join('\n')
  }

  lines.push(`      const ct = (res.headers.get('content-type') || '').toLowerCase()`)
  lines.push(`      if (!ct.includes('application/json')) {`)
  lines.push(`        expect((await res.text()).length).toBeGreaterThanOrEqual(0)`)
  lines.push(`        return`)
  lines.push(`      }`)
  lines.push(`      const data = await res.json()`)
  lines.push(`      expect(data).toBeDefined()`)

  const ex = op.responseExample
  if (ex !== null && ex !== undefined) {
    if (Array.isArray(ex)) {
      lines.push(`      expect(data).toEqual(${JSON.stringify(ex)})`)
    } else if (typeof ex === 'object') {
      lines.push(`      expect(data).toMatchObject(${JSON.stringify(ex)})`)
    } else {
      lines.push(`      expect(data).toBe(${JSON.stringify(ex)})`)
    }
  } else {
    lines.push(
      `      // Strengthen: add a response \`example\` under 2xx content in OpenAPI for toMatchObject`
    )
  }

  return lines.join('\n')
}

function escapeString(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

export function renderGraphqlStub({ runner = 'jest' }) {
  const useVitest = runner === 'vitest'
  const imp = useVitest
    ? `import { describe, it, expect } from 'vitest'\n\n`
    : ''

  return `${imp}/**
 * GraphQL smoke placeholder — replace query and variables with your schema.
 */
describe('GraphQL API', () => {
  const endpoint = () => process.env.GRAPHQL_URL || process.env.API_BASE_URL || ''

  it('posts a query', async () => {
    if (!endpoint()) throw new Error('Set GRAPHQL_URL or API_BASE_URL')

    const res = await fetch(endpoint(), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        query: \`query { __typename }\`,
        variables: {},
      }),
    })

    expect(res.status).toBeDefined()
  })
})
`
}
